name: Build
on:
  pull_request:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: ${{ github.workspace }}/app
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run ktfmt check
        run: ./gradlew ktfmtCheck

  build-debug:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: ${{ github.workspace }}/app/app/build/outputs/apk/debug/*.apk

  build-release:
    name: Build Release APK
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Retrieve keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$ENCODED_KEYSTORE" | base64 --decode > ${{ github.workspace }}/app/release.pfk
      - name: Build release APK
        env:
          KEYSTORE: ${{ github.workspace }}/app/release.pfk
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew clean assembleRelease --stacktrace
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: ${{ github.workspace }}/app/app/build/outputs/apk/release/*.apk
